In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\archive\Social_Network_Ads.csv")

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
df['Gender'] = df['Gender'].replace(['Male'],'0')
df['Gender'] = df['Gender'].replace(['Female'],'1')
df.head()

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510      0   19            19000          0
1  15810944      0   35            20000          0
2  15668575      1   26            43000          0
3  15603246      1   27            57000          0
4  15804002      0   19            76000          0

In [6]:
y = df["Purchased"]
x = df.drop("Purchased",axis=1)
x = df.drop("User ID",axis=1)

In [7]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [8]:
x = df.drop(["Purchased","User ID"],axis=1)
x

Gender  Age  EstimatedSalary
0        0   19            19000
1        0   35            20000
2        1   26            43000
3        1   27            57000
4        0   19            76000
..     ...  ...              ...
395      1   46            41000
396      0   51            23000
397      1   50            20000
398      0   36            33000
399      1   49            36000

[400 rows x 3 columns]

In [9]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)
from sklearn.linear_model import LogisticRegression

In [11]:
clr = LogisticRegression()
clr.fit(x_train, y_train)

LogisticRegression()

In [12]:
y_pred = clr.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
print(confusion_matrix(y_test, y_pred))

[[69  0]
 [31  0]]


In [15]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)

0.69


In [16]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      1.00      0.82        69
           1       0.00      0.00      0.00        31

    accuracy                           0.69       100
   macro avg       0.34      0.50      0.41       100
weighted avg       0.48      0.69      0.56       100



C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jason\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)
y_pred2 = classifier.predict(x_test)

In [18]:
print(confusion_matrix(y_test, y_pred2))
accuracy = metrics.accuracy_score(y_test, y_pred2)
print(accuracy)
print(metrics.classification_report(y_test, y_pred2))

[[61  8]
 [14 17]]
0.78
              precision    recall  f1-score   support

           0       0.81      0.88      0.85        69
           1       0.68      0.55      0.61        31

    accuracy                           0.78       100
   macro avg       0.75      0.72      0.73       100
weighted avg       0.77      0.78      0.77       100



In [19]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)
y_pred3 = dtc.predict(x_test)
y_pred3

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [20]:
print(confusion_matrix(y_test, y_pred3))
accuracy = metrics.accuracy_score(y_test, y_pred3)
print(accuracy)
print(metrics.classification_report(y_test, y_pred3))

[[62  7]
 [ 9 22]]
0.84
              precision    recall  f1-score   support

           0       0.87      0.90      0.89        69
           1       0.76      0.71      0.73        31

    accuracy                           0.84       100
   macro avg       0.82      0.80      0.81       100
weighted avg       0.84      0.84      0.84       100



In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, n_estimators=100)
classifier_rf.fit(x_train, y_train)
y_pred4 = classifier_rf.predict(x_test)
y_pred4

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [22]:
print(confusion_matrix(y_test, y_pred4))
accuracy = metrics.accuracy_score(y_test, y_pred4)
print(accuracy)
print(metrics.classification_report(y_test, y_pred4))

[[65  4]
 [ 4 27]]
0.92
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        69
           1       0.87      0.87      0.87        31

    accuracy                           0.92       100
   macro avg       0.91      0.91      0.91       100
weighted avg       0.92      0.92      0.92       100



In [23]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred5 = gnb.fit(x_train, y_train).predict(x_test)
y_pred5

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1], dtype=int64)

In [24]:
print(confusion_matrix(y_test, y_pred5))
accuracy = metrics.accuracy_score(y_test, y_pred5)
print(accuracy)
print(metrics.classification_report(y_test, y_pred5))

[[67  2]
 [ 8 23]]
0.9
              precision    recall  f1-score   support

           0       0.89      0.97      0.93        69
           1       0.92      0.74      0.82        31

    accuracy                           0.90       100
   macro avg       0.91      0.86      0.88       100
weighted avg       0.90      0.90      0.90       100



In [25]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train, y_train)
y_pred6 = mnb.fit(x_train, y_train).predict(x_test)
y_pred6

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [26]:
print(confusion_matrix(y_test, y_pred6))
accuracy = metrics.accuracy_score(y_test, y_pred6)
print(accuracy)
print(metrics.classification_report(y_test, y_pred6))

[[59 10]
 [22  9]]
0.68
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        69
           1       0.47      0.29      0.36        31

    accuracy                           0.68       100
   macro avg       0.60      0.57      0.57       100
weighted avg       0.65      0.68      0.65       100



In [63]:
df = pd.read_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\archive\Social_Network_Ads.csv")

User ID  Gender  Age  EstimatedSalary  Purchased  ScaledSalary
0  15624510    Male   19            19000          0         19000
1  15810944    Male   35            20000          0         20000
2  15668575  Female   26            43000          0         43000
3  15603246  Female   27            57000          0         57000
4  15804002    Male   19            76000          0         76000

In [67]:
ss= np.array(df[["EstimatedSalary"]])
df[["ScaledSalary"]]=ss.reshape(-1,1)
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased  ScaledSalary
0  15624510    Male   19            19000          0         19000
1  15810944    Male   35            20000          0         20000
2  15668575  Female   26            43000          0         43000
3  15603246  Female   27            57000          0         57000
4  15804002    Male   19            76000          0         76000

In [ ]:
#from sklearn.preprocessing import StandardScaler
#df[['ScaledSalary']] = df[['ScaledSalary']].apply(
#                           lambda x: StandardScaler().fit_transform(x))

In [71]:
from sklearn.preprocessing import StandardScaler
df[['ScaledSalary']] = df[['EstimatedSalary']].apply(
                           lambda x: StandardScaler().fit_transform(x))

ValueError: Expected 2D array, got 1D array instead:
array=[ 19000.  20000.  43000.  57000.  76000.  58000.  84000. 150000.  33000.
  65000.  80000.  52000.  86000.  18000.  82000.  80000.  25000.  26000.
  28000.  29000.  22000.  49000.  41000.  22000.  23000.  20000.  28000.
  30000.  43000.  18000.  74000. 137000.  16000.  44000.  90000.  27000.
  28000.  49000.  72000.  31000.  17000.  51000. 108000.  15000.  84000.
  20000.  79000.  54000. 135000.  89000.  32000.  44000.  83000.  23000.
  58000.  55000.  48000.  79000.  18000. 117000.  20000.  87000.  66000.
 120000.  83000.  58000.  19000.  82000.  63000.  68000.  80000.  27000.
  23000. 113000.  18000. 112000.  52000.  27000.  87000.  17000.  80000.
  42000.  49000.  88000.  62000. 118000.  55000.  85000.  81000.  50000.
  81000. 116000.  15000.  28000.  83000.  44000.  25000. 123000.  73000.
  37000.  88000.  59000.  86000. 149000.  21000.  72000.  35000.  89000.
  86000.  80000.  71000.  71000.  61000.  55000.  80000.  57000.  75000.
  52000.  59000.  59000.  75000.  72000.  75000.  53000.  51000.  61000.
  65000.  32000.  17000.  84000.  58000.  31000.  87000.  68000.  55000.
  63000.  82000. 107000.  59000.  25000.  85000.  68000.  59000.  89000.
  25000.  89000.  96000.  30000.  61000.  74000.  15000.  45000.  76000.
  50000.  47000.  15000.  59000.  75000.  30000. 135000. 100000.  90000.
  33000.  38000.  69000.  86000.  55000.  71000. 148000.  47000.  88000.
 115000. 118000.  43000.  72000.  28000.  47000.  22000.  23000.  34000.
  16000.  71000. 117000.  43000.  60000.  66000.  82000.  41000.  72000.
  32000.  84000.  26000.  43000.  70000.  89000.  43000.  79000.  36000.
  80000.  22000.  39000.  74000. 134000.  71000. 101000.  47000. 130000.
 114000. 142000.  22000.  96000. 150000.  42000.  58000.  43000. 108000.
  65000.  78000.  96000. 143000.  80000.  91000. 144000. 102000.  60000.
  53000. 126000. 133000.  72000.  80000. 147000.  42000. 107000.  86000.
 112000.  79000.  57000.  80000.  82000. 143000. 149000.  59000.  88000.
 104000.  72000. 146000.  50000. 122000.  52000.  97000.  39000.  52000.
 134000. 146000.  44000.  90000.  72000.  57000.  95000. 131000.  77000.
 144000. 125000.  72000.  90000. 108000.  75000.  74000. 144000.  61000.
 133000.  76000.  42000. 106000.  26000.  74000.  71000.  88000.  38000.
  36000.  88000.  61000.  70000.  21000. 141000.  93000.  62000. 138000.
  79000.  78000. 134000.  89000.  39000.  77000.  57000.  63000.  73000.
 112000.  79000. 117000.  38000.  74000. 137000.  79000.  60000.  54000.
 134000. 113000. 125000.  50000.  70000.  96000.  50000. 141000.  79000.
  75000. 104000.  55000.  32000.  60000. 138000.  82000.  52000.  30000.
 131000.  60000.  72000.  75000. 118000. 107000.  51000. 119000.  65000.
  65000.  60000.  54000. 144000.  79000.  55000. 122000. 104000.  75000.
  65000.  51000. 105000.  63000.  72000. 108000.  77000.  61000. 113000.
  75000.  90000.  57000.  99000.  34000.  70000.  72000.  71000.  54000.
 129000.  34000.  50000.  79000. 104000.  29000.  47000.  88000.  71000.
  26000.  46000.  83000.  73000. 130000.  80000.  32000.  74000.  53000.
  87000.  23000.  64000.  33000. 139000.  28000.  33000.  60000.  39000.
  71000.  34000.  35000.  33000.  23000.  45000.  42000.  59000.  41000.
  23000.  20000.  33000.  36000.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [72]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased  ScaledSalary
0  15624510    Male   19            19000          0         19000
1  15810944    Male   35            20000          0         20000
2  15668575  Female   26            43000          0         43000
3  15603246  Female   27            57000          0         57000
4  15804002    Male   19            76000          0         76000

In [49]:
x = df.drop(["Purchased","ScaledSalary", "User ID"],axis=1)
x

Gender  Age  EstimatedSalary
0        0   19        -1.490046
1        0   35        -1.460681
2        1   26        -0.785290
3        1   27        -0.374182
4        0   19         0.183751
..     ...  ...              ...
395      1   46        -0.844019
396      0   51        -1.372587
397      1   50        -1.460681
398      0   36        -1.078938
399      1   49        -0.990844

[400 rows x 3 columns]

In [50]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)
from sklearn.linear_model import LogisticRegression

In [51]:
clr = LogisticRegression()
clr.fit(x_train, y_train)

LogisticRegression()

In [54]:
y_pred7 = clr.predict(x_test)
y_pred7

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [55]:
print(confusion_matrix(y_test, y_pred7))
accuracy = metrics.accuracy_score(y_test, y_pred7)
print(accuracy)
print(metrics.classification_report(y_test, y_pred7))

[[56  8]
 [10 26]]
0.82
              precision    recall  f1-score   support

           0       0.85      0.88      0.86        64
           1       0.76      0.72      0.74        36

    accuracy                           0.82       100
   macro avg       0.81      0.80      0.80       100
weighted avg       0.82      0.82      0.82       100

